add adventisement.html, css and img (version-1)
LosanYuriy/team-proj-113 pull request #1
Opened 2024-11-16 19:47 UTC by Ryutakate

Створив першу версію моєї секції adventisement
Відправляю на перевірку чи нормально

2024-11-17 16:30 UTC, LosanYuriy requested changes

2024-11-17 16:30 UTC, LosanYuriy commented on src/partials/advertisement.html
> +    <div class="container">
div.container повинен обгортати весь контент

2024-11-17 20:19 UTC, StasSkv commented
текст і кнопка на моб та планшетній версії повинні вирівнюватись по лівому краю

маржин між текстом і посиланням повинен бути 28px для моб версії, і 32 для таб

для посилання  padding: 15px 43 px

для секції advertisement поприбирайте падінги, залиште один: для моб - padding-bottom: 60px; для таб - padding-bottom: 80px; для десктоп - padding-bottom: 100px

2024-11-18 18:52 UTC, LosanYuriy requested changes

2024-11-18 18:52 UTC, LosanYuriy commented on src/partials/advertisement.html
> +<section class="advertisement" id="advertisement">
id="advertisement"?
хто до вас повинен переходити на ваш id? якщо ніхто - то видаліть його

2024-11-18 18:52 UTC, LosanYuriy commented on src/css/advertisement.css
> +
.advertisement {
    font-family: "Gilroy", sans-serif;
    
}

.container-advertisement {
background-color: black;
    background-image: url(/img/advertisement/advertisement-mobile.webp);
    background-size: cover;
    background-position: center;
    border-radius: 30px;
    padding-bottom: 60px;
}

2024-11-18 18:52 UTC, LosanYuriy commented on src/css/advertisement.css
> +
і допрацювати щоб було як на макеті

2024-11-18 18:52 UTC, LosanYuriy commented on src/partials/advertisement.html
> +    <div class="container">
div class="container container-advertisement"
щоб .container-advertisement в css запрацював

2024-11-18 18:52 UTC, LosanYuriy commented on src/partials/advertisement.html
> +        <a href="./contact-us.html" class="advertisement-contact-link">Contact Us</a>
href="#go-contact-us"

2024-11-18 18:52 UTC, LosanYuriy commented on src/css/advertisement.css
> +
@media (min-resolution: 192dpi) {
  .container-advertisemen {
    background-color: black;
background-image: url(/img/advertisement/advertisement-mobile-2x.webp);      
  }
}

2024-11-18 18:52 UTC, LosanYuriy commented on src/css/advertisement.css
> +
@media (min-resolution: 192dpi) {
  .container-advertisement {
    background-image: url(/img/advertisement/advertisement-mobile-2x.webp);     
  }
}

2024-11-18 18:52 UTC, LosanYuriy commented on src/css/advertisement.css
> +}
видалити

2024-11-18 18:52 UTC, LosanYuriy commented on src/css/advertisement.css
> +
.container-advertisement зробити @media на мин768 и на мин 1280

2024-11-19 18:20 UTC, LosanYuriy requested changes

2024-11-19 18:20 UTC, LosanYuriy commented on src/partials/advertisement.html
> +        <a href="#go-contact-us" class="advertisement-contact-link">Contact Us</a>
3 - 7 рядки обгорнути в div class="container-advertisement"

2024-11-19 18:20 UTC, LosanYuriy commented on src/partials/advertisement.html
> +    <div class="container container-advertisement">
div class="container"

2024-11-19 18:20 UTC, LosanYuriy commented on src/css/advertisement.css
> +}
font-weight: 600;

2024-11-19 18:20 UTC, LosanYuriy commented on src/css/advertisement.css
> +}
line-height: 92%;

2024-11-19 18:20 UTC, LosanYuriy commented on src/css/advertisement.css
> +        font-size: 48px;
font-size: 48px; видалити

2024-11-19 18:20 UTC, LosanYuriy commented on src/css/advertisement.css
> +    font-weight: 700;
font-weight: 700; видалити

2024-11-19 18:20 UTC, LosanYuriy commented on src/css/advertisement.css
> +}
прописати padding-bottom: 60px;
і зробити медіа відповідно до макету (80 і 100)

2024-11-20 06:23 UTC, LosanYuriy approved these changes

2024-11-20 06:23 UTC, merged