Contacts us
LosanYuriy/team-proj-113 pull request #4
Opened 2024-11-17 15:48 UTC by Halina-Bulochnikova

2024-11-17 17:01 UTC, LosanYuriy requested changes

2024-11-17 17:01 UTC, LosanYuriy commented on src/css/container.css
> -  min-width: 320px;
/* Styles for Mobile devices */
.container {
  min-width: 320px;
  max-width: 375px;
  margin: 0 auto;
  padding: 0 20px;
}

/* Styles for Tablet devices */
@media only screen and (min-width: 768px) {
  .container {
    max-width: 768px;
    padding: 0 32px;
  }
}

/* Styles for Desktop devices */
@media only screen and (min-width: 1280px) {
  .container {
    max-width: 1280px;
    padding: 0 65px;
  }
}

2024-11-17 17:01 UTC, LosanYuriy commented on src/partials/contact-us.html
> +    <h2 class="title-contacts">Contacts Us</h2>
Conyact us

2024-11-17 17:01 UTC, LosanYuriy commented on src/css/contact-us.css
> +
не заданий шрифт
header {
  font-family: var(--font-family);
}

2024-11-17 17:01 UTC, LosanYuriy commented on src/css/contact-us.css
> +  border: 1px solid #3350e9;
якщо змінюється тільки колір то border-color: ;
у вас рамка при наведенні чорна

2024-11-17 17:01 UTC, LosanYuriy commented on src/css/contact-us.css
> +      flex-wrap: wrap;
чесно я не зрозумів що куди має переноситись в кілька рядків, якщо не вистачить? хоча вроді працює. як на мене логічніше було б flex-direction: row;

2024-11-17 17:01 UTC, LosanYuriy commented on src/css/contact-us.css
> +input::placeholder {
добавити :placeholder-shown стилізує поле введення поки воно не заповнене
, щоб воно було як в фігмі

2024-11-17 17:01 UTC, LosanYuriy commented on src/css/contact-us.css
> +  padding-bottom: 54px;
приберіть padding-bottom, через нього в текст-ареа зявляється колесо прокрутки, якого там не має бути

2024-11-17 17:01 UTC, LosanYuriy commented on src/css/contact-us.css
> +.contacts-button {
Send не вирівняно по горизонталі

2024-11-17 19:55 UTC, StasSkv commented on src/css/contact-us.css
> +  padding-bottom: 54px;
і падінг поставити padding: 12px 14px;

2024-11-17 20:03 UTC, StasSkv commented
для текстареа задайте textarea style="resize: none;
щоб користувач не міг його розтягувати сам

2024-11-17 20:41 UTC, Halina-Bulochnikova commented on src/partials/contact-us.html
> +    <h2 class="title-contacts">Contacts Us</h2>
поправила

2024-11-17 20:41 UTC, Halina-Bulochnikova commented on src/css/contact-us.css
> +
поправила

2024-11-17 20:41 UTC, Halina-Bulochnikova commented on src/css/contact-us.css
> +  border: 1px solid #3350e9;
поправила, але щось мені в тому не подобаєтьсяб прошу глянуть, то завтра якщо що зідзвонимося або на міті обговоримо

2024-11-17 20:41 UTC, Halina-Bulochnikova commented on src/css/contact-us.css
> +      flex-wrap: wrap;
від початку так робила  - не працювало, зараз змінила - запрацювало

2024-11-17 20:41 UTC, Halina-Bulochnikova commented on src/css/contact-us.css
> +input::placeholder {
додала

2024-11-17 20:41 UTC, Halina-Bulochnikova commented on src/css/contact-us.css
> +  padding-bottom: 54px;
поправила і додала

2024-11-17 20:41 UTC, Halina-Bulochnikova commented on src/css/contact-us.css
> +.contacts-button {
внесла зміни, але під питанням цей пункт

2024-11-17 20:44 UTC, Halina-Bulochnikova commented
внесла поправки, але мабуть ще треба будуть правки. Зміни запушила

2024-11-17 21:14 UTC, StasSkv commented
треба все це огорнути в тег section

не забувай за валідатор: на 87 рядку в css допиши px

2024-11-18 10:21 UTC, LosanYuriy requested changes

2024-11-18 10:21 UTC, LosanYuriy commented on src/css/container.css
> -/* Styles for Mobile devices */
у вас файл container.css пустий, докиньте в нього вміст звайла, йкий я кидав в чат проект 15,. або скопіюйте з гілки мейн з вайла container.css

2024-11-18 10:21 UTC, LosanYuriy commented on src/partials/contact-us.html
> +<div class="container contacts-container">
у вас файл container.css пустий, докиньте в нього вміст з файла, йкий я кидав в чат проект 15,. або скопіюйте з гілки мейн з файла container.css і збережіть зміни

2024-11-18 10:21 UTC, LosanYuriy commented on src/css/contact-us.css
> +.contacts-button {
.contacts-button {
display: flex;
  align-items: center;
  justify-content: center;

font-weight: 500;
font-size: 14px;
line-height: 129%;

2024-11-18 10:21 UTC, LosanYuriy commented on src/partials/contact-us.html
> +          <textarea  class="contacts-comment" style="resize: none;" name="user-comment" placeholder="Comment"></textarea>
При ховері бордер стає синім - чудово, а от при фокусі бордер чорний - потрібно допрацювати. При наведенні на інпути ховер працює як має, а з текст-ареа ефекту ховеру немає. залишилась проблема з кольором поля введеня, воно відрізняється від контейнера, в якому знаходиться, а має бути одного фону, як до рамки поля введеня, так і в середині поля введення

2024-11-18 10:21 UTC, LosanYuriy commented on src/css/contact-us.css
> +header {
має бути не header, а клас вашої секції

2024-11-18 18:56 UTC, Halina-Bulochnikova commented
Повиправляла помилки згідно ваших, Юра і Стас, уваг. Сподіваюся що нових не наробила😁З ховером і фокусом вирішено - Ларчик просто відкривався - треба додати outline: transparent; в клас інпуту.

2024-11-19 09:18 UTC, LosanYuriy requested changes

2024-11-19 09:18 UTC, LosanYuriy commented on src/css/contact-us.css
> +section {
Вирівняти код через Prettier

2024-11-19 09:18 UTC, LosanYuriy commented on src/css/contact-us.css
> +}
потрібно ще додати 
.contacts-input::placeholder {
line-height: 125%;
color: var(--main);
}

..contacts-comment::placeholder {
line-height: 125%;
color: var(--main);
}

щоб завершити стилізацію тексту підказки

2024-11-19 09:18 UTC, LosanYuriy commented on src/partials/contact-us.html
> +<section>
замінити перші два рядки на
"
section class="contacts-container"
  div class="container"
"

2024-11-19 09:18 UTC, LosanYuriy commented on src/css/contact-us.css
> +  font-family: var(--font-family);
замінити перші 5 рядків на
.contacts-container {
  font-family: var(--font-family);
  padding-bottom: 60px;
}

2024-11-19 09:18 UTC, LosanYuriy commented on src/css/contact-us.css
> +        width: 335px;
додати
 margin-top: 40px;
  margin-bottom: 40px;

2024-11-19 09:18 UTC, LosanYuriy commented on src/css/contact-us.css
> +        padding: 50px 60px;
додати
margin-top: 0;
          margin-bottom: 0;

2024-11-19 09:18 UTC, LosanYuriy commented on src/css/contact-us.css
> +  line-height: 1.29;
додати
font-size: 14px;

2024-11-19 18:14 UTC, Halina-Bulochnikova commented
Поправила. У мене встановлений Prettier ніби має автоматично все поправляти. Чи щось не так?

2024-11-19 18:32 UTC, LosanYuriy approved these changes

2024-11-19 18:47 UTC, LosanYuriy requested changes

2024-11-19 18:47 UTC, LosanYuriy commented on src/css/contact-us.css
> +  align-items: center;
display: flex; забули написати

2024-11-19 18:47 UTC, LosanYuriy commented on src/partials/contact-us.html
> +<section class="contacts-container">
/* Styles for Mobile devices */
.container {
  min-width: 320px;
  max-width: 375px;
  margin: 0 auto;
  padding: 0 20px;
}

/* Styles for Tablet devices */
@media only screen and (min-width: 768px) {
  .container {
    max-width: 768px;
    padding: 0 32px;
  }
}

/* Styles for Desktop devices */
@media only screen and (min-width: 1280px) {
  .container {
    max-width: 1280px;
    padding: 0 65px;
  }
}

2024-11-19 18:47 UTC, LosanYuriy commented on src/partials/contact-us.html
> +<section class="contacts-container">
ви внесли ці зміни в контейнер - ви великий молодець, але github здвинув колонки. зайдіть в слак, візміть звідти і скопіюйте в контейнер

2024-11-19 19:57 UTC, LosanYuriy approved these changes

2024-11-19 19:59 UTC, LosanYuriy approved these changes

2024-11-19 20:01 UTC, merged