Reviews
LosanYuriy/team-proj-113 pull request #5
Opened 2024-11-17 18:33 UTC by YLevytsk

2024-11-17 19:06 UTC, StasSkv commented
видаліть це зі свого html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/team-proj-113/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vanilla App Template</title>
    <title>Watchcharm</title>
  </head>
  <body>
  
    </body>
</html>

2024-11-17 19:12 UTC, StasSkv commented
видаліть ці стилі для 
.section-reviews {
    max-width: 320px;
    min-width: 374px;
    padding-top: 50px;
    padding-bottom: 50px;
    padding-left: 20px;
    padding-right: 20px;
    margin: 0 auto;
}

зробіть так:
 .section-reviews {
    margin-bottom: 60px;
  }

  @media screen and (min-width: 768px) {
  .section-reviews {
    margin-bottom: 80px;
  }
  }

  @media screen and (min-width: 1280px) {
  .section-reviews {
    margin-bottom: 100px;
  }
  }

2024-11-17 19:13 UTC, StasSkv commented
задайте такі стилі для .container

/* Styles for Mobile devices */
.container {
  min-width: 320px;
  max-width: 375px;
  margin: 0 auto;
  padding: 0 20px;
}

/* Styles for Tablet devices */
@media only screen and (min-width: 768px) {
  .container {
    max-width: 768px;
    padding: 0 32px;
  }
}

/* Styles for Desktop devices */
@media only screen and (min-width: 1280px) {
  .container {
    max-width: 1280px;
    padding: 0 65px;
  }
}

2024-11-17 19:16 UTC, StasSkv commented
@media screen and (min-width: 768px) {
    .reviews-list-item {
        width: calc((100% - 1* 20px) / 2);
    }
}

тут формулу трохи підправити
 width: calc((100% - 16px) / 2);

2024-11-17 19:19 UTC, StasSkv commented
у вас для h3 заданий margin-bottom 8px, а для p заданий margin-top 8px
Залиште якийсь один, а то між ними виходить 16px, а треба 8px

2024-11-17 19:28 UTC, StasSkv commented
ваш код не проходить валідацію, не закритий один з div
оцей би прибрати з коду, він не потрібен
 <div class="reviews-name">

2024-11-18 09:31 UTC, LosanYuriy requested changes

2024-11-18 09:31 UTC, LosanYuriy commented on src/partials/reviews.html
> +<html lang="en">
видалити 1-2 рядки, створює критичну помилку

2024-11-18 09:31 UTC, LosanYuriy commented on src/partials/reviews.html
> +</html>
видалити, створює критичну помилку

2024-11-18 09:31 UTC, LosanYuriy commented on src/css/reviews.css
> +  }
дублює рядки 41-44

2024-11-18 09:31 UTC, LosanYuriy commented on src/css/reviews.css
> +.section-reviews {
добав font-family: var(--font-family); щоб шрифт був як на макеті, щоб не робити це в кожному тексті, або якщо хочеш це прописувати кожен раз, то потрібно це зробити правильно font-family: 'Gilroy', sans-serif; в тебе пропущені лапки тому шрифт не спрацбовує на рядках коду 13, 22 31

2024-11-18 09:31 UTC, LosanYuriy commented on src/css/reviews.css
> +    margin-bottom: 60px;
я в чат групи проект-151скинув файл container.css, потрібно або його вміст перенести в свій контенер, або просто замінити ним свій контейнер, щоб правильно відобразились паддінги.
місце розташування src/css/container.css

2024-11-18 12:07 UTC, LosanYuriy requested changes

2024-11-18 12:07 UTC, LosanYuriy commented on src/css/reviews.css
> +.reviews-subtitle {
тут забули шрифти

2024-11-18 12:07 UTC, LosanYuriy commented on src/css/reviews.css
> +  }
з media якась біда,  в моді розробника від 320 до 375 все добре, а далі від 376 до 766 сторінка не центрована. 767 центрована. від 769 до 1279 не центрована, 1280 центрована, а далі знову збій з центруванням (зміщена до лівого краю екрана)

2024-11-18 12:07 UTC, LosanYuriy commented on src/partials/reviews.html
> +                  perfectly combined with high quality materials. The strap fits
не вирішено проблему з тим, що на макеті текст розміщений трішки інакше ніж у вас

2024-11-18 14:22 UTC, LosanYuriy approved these changes

2024-11-18 14:23 UTC, merged